"""
Analyze API Router - RAG Pipeline 集成
"""
from fastapi import APIRouter, HTTPException, Body
from pydantic import BaseModel
from typing import List, Optional, Dict
import time

router = APIRouter()


class RAGAnalyzeRequest(BaseModel):
    """RAG Pipeline 分析请求"""
    question: str
    service: Optional[str] = None
    time_range: str = "last_1h"
    metrics: Optional[List[str]] = None
    keywords: Optional[List[str]] = None


@router.post("/analyze/rag", response_model=dict)
def analyze_with_rag_pipeline(req: RAGAnalyzeRequest):
    """
    使用 RAG Pipeline 进行端到端分析
    
    完整方案：RAG + 实时数据 + 结构化 Prompt
    """
    try:
        from app.services.rag_pipeline import RAGPipeline
        
        pipeline = RAGPipeline()
        result = pipeline.analyze(
            question=req.question,
            service=req.service,
            time_range=req.time_range,
            metrics=req.metrics,
            keywords=req.keywords
        )
        
        return {
            "success": True,
            "data": result
        }
    except Exception as e:
        return {
            "success": False,
            "error": str(e)
        }


@router.post("/analyze", response_model=dict)
def analyze(req: dict):
    """
    AI 分析接口（兼容旧版）
    """
    try:
        from app.services.summary_service import run_ai_analysis
        
        result = run_ai_analysis(
            question=req.get("question", ""),
            knowledge=req.get("knowledge", []),
            metric_summary=req.get("metricSummary", ""),
            log_summary=req.get("logSummary", "")
        )
        return {
            "success": True,
            "data": result
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/analyze/rca", response_model=dict)
def analyze_rca(req: dict):
    """
    RCA 结构化分析接口
    """
    try:
        from app.services.rca_engine import RCAResult, RootCause
        from app.core.evidence_builder import EvidenceBuilder
        from app.services import knowledge_service, prometheus_service, log_service
        
        question = req.get("question", "")
        service = req.get("service", "default")
        time_range = req.get("time_range", "last_1h")
        
        # 1. 知识检索
        knowledge_results = knowledge_service.search_knowledge(question, service, top_k=3)
        
        # 2. 指标查询
        metrics_data = prometheus_service.summarize_metrics(
            service, "1h ago", "now",
            ["cpu_usage", "memory_usage", "db_connections"]
        )
        
        # 3. 日志查询
        log_lines = log_service.read_logs(service, "1h ago", "now", 
                                         ["error", "warning", "exception"], limit=20)
        logs_data = log_service.summarize_logs(log_lines)
        
        # 4. 构建上下文
        builder = EvidenceBuilder()
        context = builder.build(
            question=question,
            service=service,
            time_range=time_range,
            knowledge=knowledge_results,
            metrics=metrics_data,
            logs=logs_data
        )
        
        # 5. 执行 RCA 分析
        from app.services.rca_engine import RCAEngine
        engine = RCAEngine()
        result = engine.analyze(context)
        
        return {
            "success": True,
            "data": result.to_dict()
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/monitor", response_model=dict)
def monitor_system(metrics_summary: str = Body(...), log_summary: str = Body(...)):
    """AI 巡检接口"""
    try:
        from app.services.llm_service import call_llm
        from app.core.prompts import MONITOR_PROMPT
        
        monitor_prompt = MONITOR_PROMPT.format(
            metrics_summary=metrics_summary,
            log_summary=log_summary
        )
        result = call_llm(monitor_prompt)
        return {"success": True, "data": result}
    except Exception as e:
        return {"success": False, "message": str(e)}


@router.post("/execute_fix", response_model=dict)
def execute_fix(code: str = Body(...), scene_id: str = Body("unknown")):
    """执行修复脚本"""
    import os
    import requests
    import io
    from contextlib import redirect_stdout
    
    try:
        timestamp = int(time.time())
        script_dir = "data/scripts"
        os.makedirs(script_dir, exist_ok=True)
        script_path = os.path.join(script_dir, f"fix_{scene_id}_{timestamp}.py")
        
        with open(script_path, "w", encoding="utf-8") as f:
            f.write("# Generated by LLM-Ops Copilot\n")
            f.write(code)
        
        exec_globals = {"requests": requests}
        f_out = io.StringIO()
        with redirect_stdout(f_out):
            exec(code, exec_globals)
        
        output = f_out.getvalue()
        
        return {
            "success": True,
            "message": f"修复脚本已生成并执行: {script_path}",
            "script_path": script_path,
            "output": output
        }
    except Exception as e:
        return {"success": False, "message": f"执行失败: {str(e)}"}
